### PR TITLE
Add GpuHashJoin test cases

### PR DESCRIPTION
**Pull request by onlyindreams**
Hi,

I have created GpuHashJoin Test Cases.
This includes a test case covering #109 issue.

Regards
-----
Naoya Anzai

### CODE REVIEW

**Comment by kaigai** [comment]
comments:

1. Naming of bugfix_ghj.sql is not good, because it is unclear which bug does it try to prove.
My preference is varremap_ghj.sql, instead. Also, it shall contain the case to join two sub-
queries with a target-list with non-identical order to underlying relation.
Like:
```
  SELECT (various columns...) FROM
    (SELECT (various columns...) FROM tbl_1 limit 100) tbl_l
    JOIN
    (SELECT (various columns...) FROM tbl_2 limit 1000) tbl_r;
```

2. I want to minimize the SET enable_xxx manner to control the plan.
This test case turned off some concurrent join paths using SET enable_xxx
parameter. However, it has a risk to oversight future update of the core
planner, even if the way of cost estimation changed.
Unlike GpuPreAgg cases, GpuHashJoin has usually smaller cost than
built-in joins. It's a bit skeptical whether it is really necessary.

3. CpuReCheck may happen on not only value overflow, but zero division also.
Please add zero division case on both of integer and floating, but we don't
implement division operator on numeric type.

**Comment by onlyindreams** [comment]
kaigai-san

Thank you for comments.

I remade #109 case.
```
drop table if exists i109;
create table i109 as select generate_series(1,1000)::integer  id, 'c1'::text as c1, 'c2'::text as c2;
select b.c1,a.c2 from i109 as a inner join i109 as b on a.id=b.id limit 1;

contrib_regression=# select b.c1,a.c2 from i109 as a inner join i109 as b on a.id=b.id limit 1;
 c1 | c2 
----+----
 c2 | c1
(1 row)
```

How's that?

> GpuHashJoin has usually smaller cost than
> built-in joins. It's a bit skeptical whether it is really necessary.

In this case, a cost of GpuHashJoin is the highest out of all joins (excepting nested loop)...
```
contrib_regression=# set enable_nestloop to on;
SET
contrib_regression=# explain select b.c1,a.c2 from i109 as a inner join i109 as b on a.id=b.id limit 1;
                              QUERY PLAN                              
----------------------------------------------------------------------
 Limit  (cost=0.00..6.92 rows=1 width=64)
   ->  Nested Loop  (cost=0.00..23818.55 rows=3444 width=64)★
         Join Filter: (a.id = b.id)
         ->  Seq Scan on i109 a  (cost=0.00..18.30 rows=830 width=36)
         ->  Seq Scan on i109 b  (cost=0.00..18.30 rows=830 width=36)
(5 rows)


contrib_regression=# set enable_mergejoin to on;
SET
contrib_regression=# explain select b.c1,a.c2 from i109 as a inner join i109 as b on a.id=b.id limit 1;
                                 QUERY PLAN                                 
----------------------------------------------------------------------------
 Limit  (cost=117.08..117.10 rows=1 width=64)
   ->  Merge Join  (cost=117.08..172.91 rows=3444 width=64)★
         Merge Cond: (a.id = b.id)
         ->  Sort  (cost=58.54..60.62 rows=830 width=36)
               Sort Key: a.id
               ->  Seq Scan on i109 a  (cost=0.00..18.30 rows=830 width=36)
         ->  Sort  (cost=58.54..60.62 rows=830 width=36)
               Sort Key: b.id
               ->  Seq Scan on i109 b  (cost=0.00..18.30 rows=830 width=36)
(9 rows)

contrib_regression=# set enable_hashjoin to on;
SET
contrib_regression=# explain select b.c1,a.c2 from i109 as a inner join i109 as b on a.id=b.id limit 1;
                                 QUERY PLAN                                 
----------------------------------------------------------------------------
 Limit  (cost=28.68..28.72 rows=1 width=64)
   ->  Hash Join  (cost=28.68..169.61 rows=3444 width=64)★
         Hash Cond: (a.id = b.id)
         ->  Seq Scan on i109 a  (cost=0.00..18.30 rows=830 width=36)
         ->  Hash  (cost=18.30..18.30 rows=830 width=36)
               ->  Seq Scan on i109 b  (cost=0.00..18.30 rows=830 width=36)
(6 rows)

contrib_regression=# set enable_gpuscan to on;
SET
contrib_regression=# explain select b.c1,a.c2 from i109 as a inner join i109 as b on a.id=b.id limit 1;
                                      QUERY PLAN                                      
--------------------------------------------------------------------------------------
 Limit  (cost=528.67..528.69 rows=1 width=64)
   ->  Custom Scan (GpuHashJoin)  (cost=528.67..582.30 rows=3444 width=64)★
         Hash clause 1: (id = id)
         Bulkload: On
         ->  Custom Scan (GpuScan) on i109 a  (cost=500.00..510.00 rows=830 width=36)
         ->  Custom Scan (MultiHash)  (cost=18.30..18.30 rows=830 width=36)
               hash keys: id
               nBatches: 1  Buckets: 1000  Memory Usage: 98.78%
               ->  Seq Scan on i109 b  (cost=0.00..18.30 rows=830 width=36)
(9 rows)

contrib_regression=# set enable_gpuscan to off;
SET
contrib_regression=# explain select b.c1,a.c2 from i109 as a inner join i109 as b on a.id=b.id limit 1;
                                 QUERY PLAN                                 
----------------------------------------------------------------------------
 Limit  (cost=528.67..528.69 rows=1 width=64)
   ->  Custom Scan (GpuHashJoin)  (cost=528.67..582.30 rows=3444 width=64)★
         Hash clause 1: (id = id)
         Bulkload: Off
         ->  Seq Scan on i109 a  (cost=0.00..18.30 rows=830 width=36)
         ->  Custom Scan (MultiHash)  (cost=18.30..18.30 rows=830 width=36)
               hash keys: id
               nBatches: 1  Buckets: 1000  Memory Usage: 98.78%
               ->  Seq Scan on i109 b  (cost=0.00..18.30 rows=830 width=36)
(9 rows)
```
is startup cost  too high?

**Comment by onlyindreams** [comment]
>Please add zero division case on both of integer and floating,
All right. But I want to add the case in another new branch, so I will not add that in this request.

**Comment by kaigai** [comment]
I merged this test case at this moment. I'd like you to check whether you can run GpuHashJoin without disable other join paths, if you set gpu_setup_cost very small number (default 500.0). It prevents selection of Gpu* plan when number of rows are small.

**Pull request merged**
